version: '3.8'

services:
    bsk_ttp_service:
        build: .
        container_name: ttp_container
        ports: 
            - "8888:8887"
        networks:
            - bsk
             
networks:
    bsk:
        external: true